config/routes.rb
Rails.application.routes.draw do
  resources :visits, only: [:new, :create, :destroy]
  resources :locations
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :visits
  has_many :users, through: :visits

  def expense
    if self.admission_fee >= 50
      '💰💰💰'
    elsif self.admission_fee >= 25
      '💰💰'
    else
      '💰'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits
  has_many :locations, through: :visits
  validates :name, presence: true
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :location
  belongs_to :user

  def formatted_date
    self.created_at.strftime("%b %d, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :get_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    location = Location.create(location_params)
    redirect_to location
  end

  def edit
  end

  def update
    @location.update(location_params)
    redirect_to @location
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private

  def get_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :description, :image, :admission_fee, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
    redirect_to user_path(@user)
    else 
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def new
    @visit = Visit.new()
  end

  def create
    @visit = Visit.create(strong_params)
    redirect_to user_path(@visit.user)
  end

  def destroy
    visit = Visit.find(params[:id])
    user = visit.user
    visit.destroy
    redirect_to user_path(user)
  end

  private

  def strong_params
    params.require(:visit).permit(:user_id, :location_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trsm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Solway&display=swap" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul id='nav'>
      <li><%= link_to  "Sign Up", new_user_path %></li>
      <li><%= link_to  "All Users", users_path %></li>
      <li><%= link_to  "Locations", locations_path %></li>
      <li><%= link_to  "Log Visit", new_visit_path %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/locations/_location_form.html.erb
<div class='form-container'>
  <%= form_for @location do |l| %>
    
    <div class='form-label'>
      <%= l.label :name %>
    </div>
    <div class='form-input'>
      <%= l.text_field :name %>
    </div>

    <div class='form-label'>
      <%= l.label :description %>
    </div>
    <div class='form-input'>
      <%= l.text_area :description %>
    </div>

    <div class='form-label'>
      <%= l.label :address %>
    </div>
    <div class='form-input'>
      <%= l.text_field :address %>
    </div>

    <div class='form-label'>
      <%= l.label :image %>
    </div>
    <div class='form-input'>
      <%= l.text_field :image %>
    </div>
    
    <div class='form-label'>
      <%= l.label :'admission_fee' %>
    </div>
    <div class='form-input'>
      <%= l.number_field :'admission_fee' %>
    </div>

    <div class='form-input'>
      <%= l.submit %>
    </div>

  <% end %>
</div>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.name %></h1>

  <%= render partial: 'location_form' %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<ul>
  <% @locations.each do |location| %>
    <li><%= link_to location.name, location %> - <%= location.expense %></li>
  <% end %>
</ul>

<%= link_to 'Add New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Create a New Location!</h1>

  <%= render partial: 'location_form' %>

app/views/locations/show.html.erb
<div id='location-show'>

  <div class='header'>
    <h1><%= @location.name %></h1>
  </div>
  
  <div class='img'>
    <%= image_tag(@location.image) %>
  </div>
  
  <div class='desc'>
    <h3>Description:</h3>
    <p><%= @location.description %></p>
  </div>
  
  
  <div class='address'>
    <h3>Address:</h3>
    <p><%= @location.address %></p>
  </div>
    
  <div class='fee'>
    <% if @location.users.count == 0 %>
    <h3>Fee:</h3>
    <p>$ <%= @location.admission_fee.round %></p>
    <% else %>
    <h4><%= @location.users.count %> other(s) have enjoyed this location. For $ <%= @location.admission_fee.round %>, you can too!</h4>
    <% end %>
  </div>
  
  <div class='links'>
    <%= link_to "Edit Location", edit_location_path(@location)%> | 
    <%= link_to "Delete Location", location_path(@location), method: :delete %>
  </div>

</div>

app/views/shared/_error_form.html.erb
<% new_object.errors.full_messages.each do |error| %>
<%= error %>
<% end %>

app/views/users/_user_form.html.erb
  <% if @user.errors %>
    <%= render partial: "shared/error_form" , locals: {new_object: @user} %> 
  <%end%> 
  
  
  <div class='form-container'>
    <%= form_for @user do |u| %>
      <div class='form-label'>
        <%= u.label :name%>
      </div>
  
      <div class='form-input'>
        <%= u.text_field :name%>
      </div>

      <div class='form-input'>
        <%= u.submit%>
      </div>
    <%end%>
  </div>

app/views/users/edit.html.erb
<div id='user-form'>

  <h1> Edit <%= @user.name %> </h1>

  <%= render partial: "user_form"%>

</div>

app/views/users/index.html.erb
<h1>trsm users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div id='user-form'>

  <h1>Create a New User</h1>

  <%=render partial: "user_form"%>

</div>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<h2> Locations Visited by <%= @user.name%> </h2>

<div class='table-container'>
  <% if @user.visits.count > 0 %>
  <table>
    <tr>
      <th>Name:</th>
      <th>Date Visited</th>
      <th>Delete Visit</th>
    </tr>
    <% @user.visits.each do |visit| %>
    <tr>
      <td> <%= link_to visit.location.name, location_path(visit.location) %> </td>
      <td> <%= visit.formatted_date %></td>
      <td> <%= link_to "❌", visit_path(visit), method: :delete, data: {confirm: 'Are You Sure?'}, id: 'delete-btn' %></td>
    </tr>
    <%end %>
  </table>
  <% else %>
  <h3>No visits yet... Log a <%=link_to 'new visit', new_visit_path %> now!</h3>
  <% end %>
  
</div>

<div class='center'>
  <%= link_to "Edit User", edit_user_path(@user)%> |
  <%= link_to "Delete User", user_path(@user), method: :delete, data: {confirm: 'Are You Sure?'} %>
</div>

app/views/visits/new.html.erb
<h1>Log a New Visit</h1>

<div class='form-container'>

  <%= form_for @visit do |v| %>
    <div class='form-label'>
      <%= v.label :user %>
    </div>

    <div class='form-select'>
      <%= v.collection_select(:user_id, User.all, :id, :name) %><br />
    </div>

    <div class='form-label'>
      <%= v.label :location %>
    </div>

    <div class='form-select'>
      <%= v.collection_select(:location_id, Location.all, :id, :name) %>
    </div>

    <div class='form-input'>
      <%= v.submit %>
    </div>

  <% end %>

</div>